/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JInternalFrameBuscar.java
 *
 * Created on 24/06/2009, 10:09:09 PM
 */
package pe.edu.unmsm.fisi.supermercado.view;

import java.util.Collection;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pe.edu.unmsm.fisi.supermercado.business.ArregloProductos;
import pe.edu.unmsm.fisi.supermercado.model.Product;
import pe.edu.unmsm.fisi.supermercado.util.AppUtils;

/**
 *
 * @author soporte
 */
public class JInternalFrameBuscar extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -242730727037805381L;

    private static final Logger LOG = LoggerFactory.getLogger(JInternalFrameBuscar.class);

    private final ArregloProductos aProductos;

    private SearchType searchType;

    private enum SearchType {
        BY_CODE, BY_NAME
    }

    /**
     * Creates new form JInternalFrameBuscar
     */
    public JInternalFrameBuscar() {
        aProductos = ArregloProductos.getInstance();
        searchType = SearchType.BY_CODE;
        initComponents();
    }

    private void mostrarDatos(Collection<Product> products) {
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTableProducto.getModel();

        int rowCount = dtm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        products.forEach(p -> {
            Object[] rowData = {
                p.getCodigo(), p.getDescription(), p.getPurchaseCost(), p.getQuantityOnHand(), p.isAvailable()
            };
            dtm.addRow(rowData);
        });
        jLabelTotalRows.setText(String.valueOf(products.size()));
        jTextFieldBuscar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup = new javax.swing.ButtonGroup();
        javax.swing.JPanel jPanelBuscar = new javax.swing.JPanel();
        javax.swing.JRadioButton jRadioButtonCodigo = new javax.swing.JRadioButton();
        javax.swing.JRadioButton jRadioButtonNombre = new javax.swing.JRadioButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        javax.swing.JButton jButtonBuscar = new javax.swing.JButton();
        javax.swing.JPanel jPanelProducto = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        javax.swing.JButton jButtonSalir = new javax.swing.JButton();
        jLabelTotalRows = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Busqueda de Productos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apache_derby.png"))); // NOI18N

        jPanelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        buttonGroup.add(jRadioButtonCodigo);
        jRadioButtonCodigo.setSelected(true);
        jRadioButtonCodigo.setText("Codigo");
        jRadioButtonCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonCodigoItemStateChanged(evt);
            }
        });

        buttonGroup.add(jRadioButtonNombre);
        jRadioButtonNombre.setText("Nombre");
        jRadioButtonNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonNombreItemStateChanged(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar))
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jRadioButtonCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNombre)))
                .addContainerGap())
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCodigo)
                    .addComponent(jRadioButtonNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio Unit", "Cantidad", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProducto.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(jTableProducto);

        javax.swing.GroupLayout jPanelProductoLayout = new javax.swing.GroupLayout(jPanelProducto);
        jPanelProducto.setLayout(jPanelProductoLayout);
        jPanelProductoLayout.setHorizontalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProductoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelProductoLayout.setVerticalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProductoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelTotalRows.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTotalRows, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTotalRows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        String str = jTextFieldBuscar.getText().trim();
        if (str.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese dato a buscar", getTitle(),
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            Collection<Product> products = null;

            switch (searchType) {
                case BY_CODE:
                    int val = AppUtils.toInteger(str);
                    if (val == AppUtils.ERROR_NUMBER) {
                        LOG.warn("Ingrese entero si la busquda es por codigo");

                        AppUtils.marcarTextField(jTextFieldBuscar);
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "Ingrese entero si la busquda es por codigo",
                                getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                    } else {
                        LOG.info("Busqueda {}: '{}'", searchType, val);
                        products = aProductos.buscarCodigo(val);
                    }
                    break;

                case BY_NAME:
                    LOG.info("Busqueda {}: '{}'", searchType, str);
                    products = aProductos.buscarNombre(str);
                    break;

                default:
                    throw new IllegalArgumentException("No hay operacion definida para el tipo: " + searchType);
            }

            LOG.info("Mostrando resultado");

            if (products.isEmpty()) {
                AppUtils.marcarTextField(jTextFieldBuscar);
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se encontraron productos",
                        getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                mostrarDatos(products);
            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jRadioButtonNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonNombreItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            searchType = SearchType.BY_NAME;
            LOG.debug("Asignando tipo de busqueda por nombre");
            jTextFieldBuscar.requestFocus();
        }
    }//GEN-LAST:event_jRadioButtonNombreItemStateChanged

    private void jRadioButtonCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonCodigoItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            searchType = SearchType.BY_CODE;
            LOG.debug("Asignando tipo de busqueda por codigo");
            jTextFieldBuscar.requestFocus();
        }
    }//GEN-LAST:event_jRadioButtonCodigoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTotalRows;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
