/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JInternalFrameBuscar.java
 *
 * Created on 24/06/2009, 10:09:09 PM
 */
package pe.edu.unmsm.fisi.supermercado.view;

import java.awt.event.ItemEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pe.edu.unmsm.fisi.supermercado.business.ArregloProductos;
import pe.edu.unmsm.fisi.supermercado.model.Producto;
import pe.edu.unmsm.fisi.supermercado.util.AppUtils;

/**
 *
 * @author soporte
 */
public class JInternalFrameBuscar extends javax.swing.JInternalFrame {

    private static final Logger LOG = LoggerFactory.getLogger(JInternalFrameBuscar.class);

    private final ArregloProductos aProductos;

    private SearchType searchType;

    /**
     * Creates new form JInternalFrameBuscar
     */
    public JInternalFrameBuscar() {
        aProductos = ArregloProductos.getInstance();
        searchType = SearchType.BY_CODE;
        initComponents();
    }

    private void mostrarDatos(Producto p) {
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTableProducto.getModel();
        jTableProducto.setModel(dtm);
        Object[] rowData = {
            p.getCodigo(), p.getNombre(), p.getPrecUnit(), p.getCantidad()
        };
        dtm.addRow(rowData);
        jTextFieldBuscar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanelBuscar = new javax.swing.JPanel();
        jRadioButtonCodigo = new javax.swing.JRadioButton();
        jRadioButtonNombre = new javax.swing.JRadioButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jPanelProducto = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jButtonSalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Busqueda de Productos");

        jPanelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        buttonGroup.add(jRadioButtonCodigo);
        jRadioButtonCodigo.setSelected(true);
        jRadioButtonCodigo.setText("Codigo");
        jRadioButtonCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonCodigoItemStateChanged(evt);
            }
        });

        buttonGroup.add(jRadioButtonNombre);
        jRadioButtonNombre.setText("Nombre");
        jRadioButtonNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonNombreItemStateChanged(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar))
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jRadioButtonCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNombre)))
                .addContainerGap())
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCodigo)
                    .addComponent(jRadioButtonNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio Unit", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProducto.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(jTableProducto);

        javax.swing.GroupLayout jPanelProductoLayout = new javax.swing.GroupLayout(jPanelProducto);
        jPanelProducto.setLayout(jPanelProductoLayout);
        jPanelProductoLayout.setHorizontalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelProductoLayout.setVerticalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProductoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        String str = jTextFieldBuscar.getText().trim();
        if (str.length() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese dato a buscar", getTitle(),
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            Producto producto = null;

            switch (searchType) {
                case BY_CODE:
                    int val = AppUtils.toInteger(str);
                    if (val == AppUtils.ERROR_NUMBER) {
                        AppUtils.marcarTextField(jTextFieldBuscar);
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "Ingrese entero si la busquda es por codigo",
                                getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);
                    } else {
                        producto = aProductos.buscarCodigo(val);
                    }
                    LOG.info("Busqueda {}: '{}'", searchType, val);
                    break;

                case BY_NAME:
                    LOG.info("Busqueda {}: '{}'", searchType, str);
                    producto = aProductos.buscarNombre(str);
                    break;

                default:
                    throw new IllegalArgumentException("No hay operacion definida para el tipo: " + searchType);
            }

            if (producto == null) {
                AppUtils.marcarTextField(jTextFieldBuscar);
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se puede encontrar el producto",
                        getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                mostrarDatos(producto);
            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jRadioButtonNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonNombreItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            searchType = SearchType.BY_NAME;
            LOG.debug("Asignando tipo de busqueda por nombre");
        }
    }//GEN-LAST:event_jRadioButtonNombreItemStateChanged

    private void jRadioButtonCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonCodigoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            searchType = SearchType.BY_CODE;
            LOG.debug("Asignando tipo de busqueda por codigo");
        }
    }//GEN-LAST:event_jRadioButtonCodigoItemStateChanged

    private enum SearchType {
        BY_CODE, BY_NAME
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelProducto;
    private javax.swing.JRadioButton jRadioButtonCodigo;
    private javax.swing.JRadioButton jRadioButtonNombre;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
