/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Main.java
 *
 * Created on 24/06/2009, 08:39:57 PM
 */
package pe.edu.unmsm.fisi.supermercado.view;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import pe.edu.unmsm.fisi.supermercado.util.AppUtils;

/**
 * @author Eliana Zapata
 * @since 2009
 */
public class Main extends javax.swing.JFrame {

    private static final long serialVersionUID = -7967665231395260595L;

    private static final Logger LOG = LoggerFactory.getLogger(Main.class);

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jInternalFrameCustomers = new JInternalFrameCustomers();
        jInternalFrameBuscar = new JInternalFrameBuscar();
        jInternalFrameVentas = new JInternalFrameVentas();
        javax.swing.JMenuBar jMenuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenuMantenimiento = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItemClientes = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemBuscar = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemVentas = new javax.swing.JMenuItem();
        javax.swing.JSeparator jSeparator = new javax.swing.JSeparator();
        javax.swing.JMenuItem jMenuItemSalir = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenuAyuda = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supermercado");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/apache_derby.png")).getImage());

        jDesktopPane.setBackground(new java.awt.Color(26, 185, 241));

        jMenuMantenimiento.setText("Archivo");

        jMenuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemClientes);

        jMenuItemBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBuscar.setText("Productos");
        jMenuItemBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemBuscar);

        jMenuItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVentas.setText("Ventas");
        jMenuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVentasActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemVentas);
        jMenuMantenimiento.add(jSeparator);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemSalir);

        jMenuBar.add(jMenuMantenimiento);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemAcercaDe.setText("Acerca de");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        LOG.trace(evt.paramString());
        AppUtils.displayInternalFrame(jDesktopPane, jInternalFrameCustomers);
        LOG.debug("Mostrando frame interno de regisro de clientes");
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarActionPerformed
        LOG.trace(evt.paramString());
        AppUtils.displayInternalFrame(jDesktopPane, jInternalFrameBuscar);
        LOG.debug("Mostrando frame interno de busqueda de productos");
    }//GEN-LAST:event_jMenuItemBuscarActionPerformed

    private void jMenuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVentasActionPerformed
        LOG.trace(evt.paramString());
        AppUtils.displayInternalFrame(jDesktopPane, jInternalFrameVentas);
        LOG.debug("Mostrando frame interno de venta de productos");
    }//GEN-LAST:event_jMenuItemVentasActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        LOG.trace(evt.paramString());
        int optionChosen = javax.swing.JOptionPane.showConfirmDialog(this,
                "Seguro que desea salir?", getTitle(),
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (javax.swing.JOptionPane.YES_OPTION == optionChosen) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        LOG.trace(evt.paramString());
        new JDialogAcercaDe(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private JInternalFrameCustomers jInternalFrameCustomers;
    private JInternalFrameBuscar jInternalFrameBuscar;
    private JInternalFrameVentas jInternalFrameVentas;
    // End of variables declaration//GEN-END:variables
}
