/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Main.java
 *
 * Created on 24/06/2009, 08:39:57 PM
 */
package pe.edu.unmsm.fisi.supermercado.view;

import pe.edu.unmsm.fisi.supermercado.business.ArregloProductos;

/**
 *
 * @author Eliana Zapata
 * @since 2009
 */
public class Main extends javax.swing.JFrame {

    private final ArregloProductos aProductos;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        aProductos = ArregloProductos.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        javax.swing.JMenuBar jMenuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenuMantenimiento = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItemInsertar = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemBuscar = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemVentas = new javax.swing.JMenuItem();
        javax.swing.JSeparator jSeparator = new javax.swing.JSeparator();
        javax.swing.JMenuItem jMenuItemSalir = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenuAyuda = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supermercado");

        jDesktopPane.setBackground(new java.awt.Color(26, 185, 241));

        jMenuMantenimiento.setText("Archivo");

        jMenuItemInsertar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemInsertar.setText("Insertar");
        jMenuItemInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertarActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemInsertar);

        jMenuItemBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBuscar.setText("Buscar");
        jMenuItemBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemBuscar);

        jMenuItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVentas.setText("Ventas");
        jMenuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVentasActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemVentas);
        jMenuMantenimiento.add(jSeparator);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemSalir);

        jMenuBar.add(jMenuMantenimiento);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAcercaDe.setText("Acerca de");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertarActionPerformed
        // TODO add your handling code here:
        jInternalFrameInsertar = new JInternalFrameInsertar();
        jDesktopPane.add(jInternalFrameInsertar);
        jInternalFrameInsertar.setVisible(true);
    }//GEN-LAST:event_jMenuItemInsertarActionPerformed

    private void jMenuItemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarActionPerformed
        // TODO add your handling code here:
        if (aProductos.numElementos() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No existen productos para poder iniciar la busqueda",
                    getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            jInternalFrameBuscar = new JInternalFrameBuscar();
            jDesktopPane.add(jInternalFrameBuscar);
            jInternalFrameBuscar.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemBuscarActionPerformed

    private void jMenuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVentasActionPerformed
        // TODO add your handling code here:
        if (aProductos.numElementos() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No existen productos para poder iniciar la venta",
                    getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            jInternalFrameVentas = new JInternalFrameVentas();
            jDesktopPane.add(jInternalFrameVentas);
            jInternalFrameVentas.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemVentasActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        int i = javax.swing.JOptionPane.showConfirmDialog(this,
                "Seguro que desea salir?", getTitle(),
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (i == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        // TODO add your handling code here:
        new JDialogAcercaDe(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private JInternalFrameInsertar jInternalFrameInsertar;
    private JInternalFrameBuscar jInternalFrameBuscar;
    private JInternalFrameVentas jInternalFrameVentas;
    // End of variables declaration//GEN-END:variables
}
