/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.unmsm.fisi.market.view;

import pe.edu.unmsm.fisi.market.model.Product;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pe.edu.unmsm.fisi.market.business.ProductsBusiness;
import pe.edu.unmsm.fisi.market.model.Manufacturer;
import pe.edu.unmsm.fisi.market.model.ProductCode;
import pe.edu.unmsm.fisi.market.util.AppUtils;

/**
 *
 * @author Cesardl
 */
public class JDialogProductForm extends javax.swing.JDialog {

    private static final Logger LOG = LoggerFactory.getLogger(JDialogProductForm.class);

    private String nombre;
    private double precUnit;
    private int codigo, cant;
    private Product product;
    private final ProductsBusiness productBusiness;

    /**
     * @inheritDoc
     */
    public JDialogProductForm(java.awt.Frame parent) {
        super(parent);

        productBusiness = ProductsBusiness.getInstance();

        initComponents();
    }

    private boolean capturaDatos() {
        codigo = AppUtils.toInteger(jTextFieldProductId.getText().trim());
        nombre = jTextFieldNombre.getText().trim();
        precUnit = AppUtils.toDouble(jTextFieldPrecUnit.getText().trim());
        cant = AppUtils.toInteger(String.valueOf(jSpinnerCantidad.getValue()));
        if (codigo == AppUtils.ERROR_NUMBER) {
            AppUtils.marcarTextField(jTextFieldProductId);
            return false;
        }
        if (nombre.length() == 0) {
            AppUtils.marcarTextField(jTextFieldNombre);
            return false;
        }
        if (precUnit == AppUtils.ERROR_NUMBER) {
            AppUtils.marcarTextField(jTextFieldPrecUnit);
            return false;
        }
        if (cant == AppUtils.ERROR_NUMBER || cant == 0) {
            jSpinnerCantidad.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel = new javax.swing.JPanel();
        jLabelManufacturer = new javax.swing.JLabel();
        javax.swing.JLabel jLabelProductId = new javax.swing.JLabel();
        javax.swing.JLabel jLabelTipo = new javax.swing.JLabel();
        javax.swing.JLabel jLabelNombre = new javax.swing.JLabel();
        javax.swing.JLabel jLabelPrecUnit = new javax.swing.JLabel();
        javax.swing.JLabel jLabelCantidad = new javax.swing.JLabel();
        jComboBoxManufacturer = new javax.swing.JComboBox<>();
        jTextFieldProductId = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPrecUnit = new javax.swing.JTextField();
        jSpinnerCantidad = new javax.swing.JSpinner();
        javax.swing.JButton jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Producto");
        setModal(true);
        setResizable(false);

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Producto"));

        jLabelManufacturer.setText("Manufacturer");

        jLabelProductId.setText("Codigo");

        jLabelTipo.setText("Tipo");

        jLabelNombre.setText("Descripcion");

        jLabelPrecUnit.setText("Precio Unitario");

        jLabelCantidad.setText("Cantidad");

        jComboBoxManufacturer.setModel(new javax.swing.DefaultComboBoxModel<>(new java.util.Vector<>(productBusiness.getManufacturers())));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new java.util.Vector<>(productBusiness.getProductCodes())));

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipo)
                    .addComponent(jLabelManufacturer)
                    .addComponent(jLabelProductId)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelPrecUnit))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerCantidad)
                    .addComponent(jTextFieldPrecUnit)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jComboBoxTipo, 0, 261, Short.MAX_VALUE)
                    .addComponent(jTextFieldProductId)
                    .addComponent(jComboBoxManufacturer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelCantidad)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelManufacturer)
                    .addComponent(jComboBoxManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelProductId)
                    .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldPrecUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCantidad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAdd.setText("Agregar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAdd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setProduct(Product product) {
        this.product = product;

        jTextFieldProductId.setText(String.valueOf(product.getProductId()));
        jTextFieldNombre.setText(product.getDescription());
        jTextFieldPrecUnit.setText(String.valueOf(product.getPurchaseCost()));
        jSpinnerCantidad.setValue(product.getQuantityOnHand());
    }

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        LOG.trace(evt.paramString());
        if (capturaDatos()) {
            if (productBusiness.aniadirProducto(product)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Se agrego el producto correctamente!",
                        getTitle(), javax.swing.JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se puede agregar el producto!\nCodigo repetido!",
                        getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
                AppUtils.marcarTextField(jTextFieldProductId);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese correctamente los datos",
                    getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Manufacturer> jComboBoxManufacturer;
    private javax.swing.JComboBox<ProductCode> jComboBoxTipo;
    private javax.swing.JLabel jLabelManufacturer;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecUnit;
    private javax.swing.JTextField jTextFieldProductId;
    // End of variables declaration//GEN-END:variables
}
