/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.unmsm.fisi.market.view;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pe.edu.unmsm.fisi.market.business.impl.CustomerBusiness;
import pe.edu.unmsm.fisi.market.model.Customer;
import pe.edu.unmsm.fisi.market.model.DiscountCode;
import pe.edu.unmsm.fisi.market.model.MicroMarket;

/**
 *
 * @author Cesardl
 */
public class JDialogCustomerForm extends javax.swing.JDialog {

    private static final long serialVersionUID = 1832568877971046252L;

    private static final Logger LOG = LoggerFactory.getLogger(JDialogCustomerForm.class);

    private final Customer customer;
    private final CustomerBusiness customerBusiness;

    private boolean actionPerformed;

    /**
     * @inheritDoc
     */
    public JDialogCustomerForm(java.awt.Frame parent, Customer customer) {
        super(parent);

        this.customerBusiness = CustomerBusiness.getInstance();
        this.customer = customer;
        this.actionPerformed = false;

        initComponents();
    }

    public boolean isActionPerformed() {
        return actionPerformed;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel labelId = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        javax.swing.JLabel labelDiscountCode = new javax.swing.JLabel();
        comboBoxDiscountCode = new javax.swing.JComboBox<>();
        javax.swing.JLabel labelMicroMarket = new javax.swing.JLabel();
        comboBoxMicroMarket = new javax.swing.JComboBox<>();
        javax.swing.JLabel labelName = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        javax.swing.JLabel labelDirectionMain = new javax.swing.JLabel();
        textFieldDirectionMain = new javax.swing.JTextField();
        javax.swing.JLabel labelDirectionExtension = new javax.swing.JLabel();
        textFieldDirectionExtension = new javax.swing.JTextField();
        javax.swing.JLabel labelCity = new javax.swing.JLabel();
        textFieldCity = new javax.swing.JTextField();
        javax.swing.JLabel labelState = new javax.swing.JLabel();
        textFieldState = new javax.swing.JTextField();
        javax.swing.JLabel labelPhone = new javax.swing.JLabel();
        textFieldPhone = new javax.swing.JTextField();
        javax.swing.JLabel labelFax = new javax.swing.JLabel();
        textFieldFax = new javax.swing.JTextField();
        javax.swing.JLabel labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        javax.swing.JLabel labelCreditLine = new javax.swing.JLabel();
        textFieldCreditLine = new javax.swing.JTextField();
        javax.swing.JButton buttonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalle de Cliente");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/apache_derby.png")).getImage());
        setModal(true);
        setResizable(false);

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelId.setText("Id");

        textFieldId.setEnabled(false);

        labelDiscountCode.setText("Descuento");

        comboBoxDiscountCode.setFocusable(false);

        labelMicroMarket.setText("ZIP");

        comboBoxMicroMarket.setFocusable(false);

        labelName.setText("Nombre");

        labelDirectionMain.setText("Direccion (principal)");

        labelDirectionExtension.setText("Direccion (extensión)");

        labelCity.setText("Ciudad");

        labelState.setText("Estado");

        labelPhone.setText("Telefono");

        labelFax.setText("Fax");

        labelEmail.setText("E-mail");

        labelCreditLine.setText("Línea de crédito");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDiscountCode)
                    .addComponent(labelId)
                    .addComponent(labelMicroMarket)
                    .addComponent(labelName)
                    .addComponent(labelDirectionMain)
                    .addComponent(labelDirectionExtension)
                    .addComponent(labelCity)
                    .addComponent(labelState)
                    .addComponent(labelPhone)
                    .addComponent(labelFax)
                    .addComponent(labelEmail)
                    .addComponent(labelCreditLine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDiscountCode, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMicroMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDirectionMain, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDirectionExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCreditLine, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(comboBoxDiscountCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiscountCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMicroMarket)
                    .addComponent(comboBoxMicroMarket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDirectionMain)
                    .addComponent(textFieldDirectionMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDirectionExtension)
                    .addComponent(textFieldDirectionExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCity)
                    .addComponent(textFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelState)
                    .addComponent(textFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhone)
                    .addComponent(textFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFax)
                    .addComponent(textFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCreditLine)
                    .addComponent(textFieldCreditLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonSave.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setVisible(boolean b) {
        if (b) {
            comboBoxDiscountCode.setModel(
                    new javax.swing.DefaultComboBoxModel<>(
                            new java.util.Vector<>(customerBusiness.getDiscountCodes())));

            comboBoxMicroMarket.setModel(
                    new javax.swing.DefaultComboBoxModel<>(
                            new java.util.Vector<>(customerBusiness.getMicroMarkets())));

            if (customer.getCustomerId() != null) {
                showData();
            }
        }

        super.setVisible(b);
    }

    private void showData() {
        textFieldId.setText(String.valueOf(customer.getCustomerId()));

        for (int index = 0; index < comboBoxDiscountCode.getItemCount(); index++) {
            DiscountCode dc = comboBoxDiscountCode.getItemAt(index);
            if (dc.getDiscountCode().equals(customer.getDiscountCode().getDiscountCode())) {
                comboBoxDiscountCode.setSelectedItem(dc);
                break;
            }
        }

        for (int index = 0; index < comboBoxMicroMarket.getItemCount(); index++) {
            MicroMarket mm = comboBoxMicroMarket.getItemAt(index);
            if (mm.getZipCode().equals(customer.getMicroMarket().getZipCode())) {
                comboBoxMicroMarket.setSelectedItem(mm);
                break;
            }
        }

        textFieldName.setText(customer.getName());
        textFieldDirectionMain.setText(customer.getAddressLine1());
        textFieldDirectionExtension.setText(customer.getAddressLine2());
        textFieldCity.setText(customer.getCity());
        textFieldState.setText(customer.getState());
        textFieldPhone.setText(customer.getPhone());
        textFieldFax.setText(customer.getFax());
        textFieldEmail.setText(customer.getEmail());
        textFieldCreditLine.setText(String.valueOf(customer.getCreditLimit()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<DiscountCode> comboBoxDiscountCode;
    private javax.swing.JComboBox<MicroMarket> comboBoxMicroMarket;
    private javax.swing.JTextField textFieldCity;
    private javax.swing.JTextField textFieldCreditLine;
    private javax.swing.JTextField textFieldDirectionExtension;
    private javax.swing.JTextField textFieldDirectionMain;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldFax;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldPhone;
    private javax.swing.JTextField textFieldState;
    // End of variables declaration//GEN-END:variables
}
