/*
 * JFrameMain.java
 *
 * Created on 24/06/2009, 08:39:57 PM
 */
package pe.edu.unmsm.fisi.market.view;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pe.edu.unmsm.fisi.market.util.AppUtils;

/**
 * @author Eliana Zapata
 * @since 2009
 */
public class JFrameMain extends javax.swing.JFrame {

    private static final long serialVersionUID = -7967665231395260595L;

    private static final Logger LOG = LoggerFactory.getLogger(JFrameMain.class);

    /**
     * Creates new form Main
     */
    public JFrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu menuMaintenance = new javax.swing.JMenu();
        javax.swing.JMenuItem menuItemCustomers = new javax.swing.JMenuItem();
        javax.swing.JMenuItem menuItemProducts = new javax.swing.JMenuItem();
        javax.swing.JMenuItem menuItemPurchaseOrders = new javax.swing.JMenuItem();
        javax.swing.JSeparator separator = new javax.swing.JSeparator();
        javax.swing.JMenuItem menuItemExit = new javax.swing.JMenuItem();
        javax.swing.JMenu menuHelp = new javax.swing.JMenu();
        javax.swing.JMenuItem menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tech Market");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/apache_derby.png")).getImage());

        internalFrameCustomers = new JInternalFrameCustomers();
        internalFrameProducts = new JInternalFrameProducts();
        internalFramePurchaseOrders = new JInternalFramePurchaseOrders();
        desktopPane.setBackground(new java.awt.Color(26, 185, 241));

        menuMaintenance.setText("Archivo");

        menuItemCustomers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuItemCustomers.setText("Clientes");
        menuItemCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCustomersActionPerformed(evt);
            }
        });
        menuMaintenance.add(menuItemCustomers);

        menuItemProducts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuItemProducts.setText("Productos");
        menuItemProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProductsActionPerformed(evt);
            }
        });
        menuMaintenance.add(menuItemProducts);

        menuItemPurchaseOrders.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuItemPurchaseOrders.setText("Ventas");
        menuItemPurchaseOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPurchaseOrdersActionPerformed(evt);
            }
        });
        menuMaintenance.add(menuItemPurchaseOrders);
        menuMaintenance.add(separator);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemExit.setText("Salir");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuMaintenance.add(menuItemExit);

        menuBar.add(menuMaintenance);

        menuHelp.setText("Ayuda");

        menuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItemAbout.setText("Acerca de");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCustomersActionPerformed
        LOG.trace(evt.paramString());
        AppUtils.displayInternalFrame(desktopPane, internalFrameCustomers);
        LOG.debug("Mostrando frame interno de regisro de clientes");
    }//GEN-LAST:event_menuItemCustomersActionPerformed

    private void menuItemProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProductsActionPerformed
        LOG.trace(evt.paramString());
        AppUtils.displayInternalFrame(desktopPane, internalFrameProducts);
        LOG.debug("Mostrando frame interno de busqueda de productos");
    }//GEN-LAST:event_menuItemProductsActionPerformed

    private void menuItemPurchaseOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPurchaseOrdersActionPerformed
        LOG.trace(evt.paramString());
        AppUtils.displayInternalFrame(desktopPane, internalFramePurchaseOrders);
        LOG.debug("Mostrando frame interno de venta de productos");
    }//GEN-LAST:event_menuItemPurchaseOrdersActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        LOG.trace(evt.paramString());
        int optionChosen = javax.swing.JOptionPane.showConfirmDialog(this,
                "Seguro que desea salir?", getTitle(),
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (javax.swing.JOptionPane.YES_OPTION == optionChosen) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        LOG.trace(evt.paramString());
        JDialogAbout dialog = new JDialogAbout(this);
        dialog.setTitle(getTitle());
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private JInternalFrameCustomers internalFrameCustomers;
    private JInternalFrameProducts internalFrameProducts;
    private JInternalFramePurchaseOrders internalFramePurchaseOrders;
    // End of variables declaration//GEN-END:variables
}
