/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JInternalFrameProducts.java
 *
 * Created on 24/06/2009, 10:09:09 PM
 */
package pe.edu.unmsm.fisi.market.view;

import java.util.Collection;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pe.edu.unmsm.fisi.market.business.ProductsBusiness;
import pe.edu.unmsm.fisi.market.model.Product;
import pe.edu.unmsm.fisi.market.util.AppUtils;

/**
 *
 * @author soporte
 */
public class JInternalFrameProducts extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -242730727037805381L;

    private static final Logger LOG = LoggerFactory.getLogger(JInternalFrameProducts.class);

    private final ProductsBusiness aProductos;

    private SearchType searchType;

    private enum SearchType {
        BY_CODE, BY_NAME
    }

    /**
     * Creates new form JInternalFrameBuscar
     */
    public JInternalFrameProducts() {
        aProductos = ProductsBusiness.getInstance();
        searchType = SearchType.BY_CODE;
        initComponents();
    }

    private void mostrarDatos(Collection<Product> products) {
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTableProducto.getModel();

        int rowCount = dtm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        products.forEach(p -> {
            Object[] rowData = {
                p.getProductId(), p.getDescription(), p.getPurchaseCost(), p.getQuantityOnHand(), p.isAvailable()
            };
            dtm.addRow(rowData);
        });
        jLabelTotalRows.setText(String.valueOf(products.size()));
        jTextFieldBuscar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup = new javax.swing.ButtonGroup();
        javax.swing.JPanel jPanelSearch = new javax.swing.JPanel();
        javax.swing.JRadioButton jRadioButtonCodigo = new javax.swing.JRadioButton();
        javax.swing.JRadioButton jRadioButtonNombre = new javax.swing.JRadioButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        javax.swing.JPanel jPanelProduct = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        javax.swing.JLabel jLabelTotal = new javax.swing.JLabel();
        jLabelTotalRows = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Busqueda de Productos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apache_derby.png"))); // NOI18N

        jPanelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        buttonGroup.add(jRadioButtonCodigo);
        jRadioButtonCodigo.setSelected(true);
        jRadioButtonCodigo.setText("Codigo");
        jRadioButtonCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonCodigoItemStateChanged(evt);
            }
        });

        buttonGroup.add(jRadioButtonNombre);
        jRadioButtonNombre.setText("Nombre");
        jRadioButtonNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonNombreItemStateChanged(evt);
            }
        });

        jButtonSearch.setText("Buscar");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch)
                .addContainerGap())
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCodigo)
                    .addComponent(jRadioButtonNombre)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanelProduct.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio Unit", "Cantidad", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProducto.getTableHeader().setReorderingAllowed(false);
        jTableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductoMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(jTableProducto);

        javax.swing.GroupLayout jPanelProductLayout = new javax.swing.GroupLayout(jPanelProduct);
        jPanelProduct.setLayout(jPanelProductLayout);
        jPanelProductLayout.setHorizontalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProductLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelProductLayout.setVerticalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProductLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButtonAdd.setText("Agregar Producto");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });

        jLabelTotal.setText("Total:");

        jLabelTotalRows.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalRows.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotalRows)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalRows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdd)
                    .addComponent(jLabelTotal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        LOG.trace(evt.paramString());

        if (evt.getSource().equals(jButtonSearch)) {
            searchProduct();
        } else if (evt.getSource().equals(jButtonAdd)) {
            addProduct();
        }
    }//GEN-LAST:event_productActionPerformed

    private void searchProduct() {
        LOG.debug("Searching product");
        String str = jTextFieldBuscar.getText().trim();
        if (str.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese dato a buscar", getTitle(),
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            Collection<Product> products;

            switch (searchType) {
                case BY_CODE:
                    int val = AppUtils.toInteger(str);
                    if (val == AppUtils.ERROR_NUMBER) {
                        LOG.warn("Ingrese entero si la busquda es por codigo");

                        AppUtils.marcarTextField(jTextFieldBuscar);
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "Ingrese entero si la busquda es por codigo",
                                getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                    } else {
                        LOG.info("Busqueda {}: '{}'", searchType, val);
                        Product product = aProductos.buscarCodigo(val);

                        products = product == null
                                ? Collections.emptyList()
                                : Collections.singletonList(product);
                    }
                    break;

                case BY_NAME:
                    LOG.info("Busqueda {}: '{}'", searchType, str);
                    products = aProductos.buscarNombre(str);
                    break;

                default:
                    throw new IllegalArgumentException("No hay operacion definida para el tipo: " + searchType);
            }

            LOG.info("Mostrando resultado");

            if (products.isEmpty()) {
                AppUtils.marcarTextField(jTextFieldBuscar);
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se encontraron productos",
                        getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                mostrarDatos(products);
            }
        }
    }

    private void addProduct() {
        LOG.debug("Adding product");
        JDialogProductForm productForm
                = new JDialogProductForm(javax.swing.JOptionPane.getFrameForComponent(this));
        productForm.setVisible(true);
    }

    private void jRadioButtonNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonNombreItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            searchType = SearchType.BY_NAME;
            LOG.debug("Asignando tipo de busqueda por nombre");
            jTextFieldBuscar.requestFocus();
        }
    }//GEN-LAST:event_jRadioButtonNombreItemStateChanged

    private void jRadioButtonCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonCodigoItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            searchType = SearchType.BY_CODE;
            LOG.debug("Asignando tipo de busqueda por codigo");
            jTextFieldBuscar.requestFocus();
        }
    }//GEN-LAST:event_jRadioButtonCodigoItemStateChanged

    private void jTableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductoMouseClicked
        LOG.trace(evt.paramString());

        if (evt.getClickCount() == 2) {
            javax.swing.JTable target = (javax.swing.JTable) evt.getSource();
            int row = target.getSelectedRow();

            DefaultTableModel dtm = (DefaultTableModel) target.getModel();

            int productId = (Integer) dtm.getValueAt(row, 0);
            LOG.debug("Getting product identifier {}", productId);

            Product product = aProductos.buscarCodigo(productId);
            JDialogProductForm productForm
                    = new JDialogProductForm(javax.swing.JOptionPane.getFrameForComponent(this));
            productForm.setProduct(product);
            System.out.println("Dialog inicializado, a exponer");
            productForm.setVisible(true);
            System.out.println("ya se expuso, ahora?");
        }
    }//GEN-LAST:event_jTableProductoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelTotalRows;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
