/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JInternalFrameProducts.java
 *
 * Created on 24/06/2009, 10:09:09 PM
 */
package pe.edu.unmsm.fisi.market.view;

import java.util.Collection;
import java.util.Collections;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pe.edu.unmsm.fisi.market.business.ProductsBusiness;
import pe.edu.unmsm.fisi.market.model.Product;
import pe.edu.unmsm.fisi.market.util.AppUtils;

/**
 *
 * @author soporte
 */
public class JInternalFrameProducts extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -242730727037805381L;

    private static final Logger LOG = LoggerFactory.getLogger(JInternalFrameProducts.class);

    private final ProductsBusiness aProductos;

    private SearchType searchType;

    private enum SearchType {
        BY_CODE, BY_NAME
    }

    /**
     * Creates new form JInternalFrameBuscar
     */
    public JInternalFrameProducts() {
        aProductos = ProductsBusiness.getInstance();
        searchType = SearchType.BY_NAME;
        initComponents();
    }

    private void mostrarDatos(Collection<Product> products) {
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tableProducts.getModel();

        int rowCount = dtm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        products.forEach(p -> {
            Object[] rowData = {
                p.getProductId(), p.getDescription(), p.getPurchaseCost(), p.getQuantityOnHand(), p.isAvailable(), p.getManufacturer().getName()
            };
            dtm.addRow(rowData);
        });
        labelTotalRows.setText(String.valueOf(products.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup = new javax.swing.ButtonGroup();
        javax.swing.JPanel panelSearch = new javax.swing.JPanel();
        javax.swing.JRadioButton radioButtonCodigo = new javax.swing.JRadioButton();
        javax.swing.JRadioButton radioButtonNombre = new javax.swing.JRadioButton();
        textFieldBuscar = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        javax.swing.JPanel panelProduct = new javax.swing.JPanel();
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        javax.swing.JLabel labelTotal = new javax.swing.JLabel();
        labelTotalRows = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Busqueda de Productos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apache_derby.png"))); // NOI18N

        panelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        buttonGroup.add(radioButtonCodigo);
        radioButtonCodigo.setText("Codigo");
        radioButtonCodigo.setFocusable(false);
        radioButtonCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonCodigoItemStateChanged(evt);
            }
        });

        buttonGroup.add(radioButtonNombre);
        radioButtonNombre.setSelected(true);
        radioButtonNombre.setText("Nombre");
        radioButtonNombre.setFocusable(false);
        radioButtonNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonNombreItemStateChanged(evt);
            }
        });

        buttonSearch.setText("Buscar");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtonCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSearch)
                .addContainerGap())
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonCodigo)
                    .addComponent(radioButtonNombre)
                    .addComponent(textFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        textFieldBuscar.requestFocus();

        panelProduct.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio Unit", "Cantidad", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProducts.getTableHeader().setReorderingAllowed(false);
        tableProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductsMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(tableProducts);

        javax.swing.GroupLayout panelProductLayout = new javax.swing.GroupLayout(panelProduct);
        panelProduct.setLayout(panelProductLayout);
        panelProductLayout.setHorizontalGroup(
            panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelProductLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelProductLayout.setVerticalGroup(
            panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelProductLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        buttonAdd.setText("Agregar Producto");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });

        labelTotal.setText("Total:");

        labelTotalRows.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalRows.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTotalRows)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalRows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAdd)
                    .addComponent(labelTotal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        LOG.trace(evt.paramString());

        if (evt.getSource().equals(buttonSearch)) {
            searchProduct();
        } else if (evt.getSource().equals(buttonAdd)) {
            addProduct();
        }
    }//GEN-LAST:event_productActionPerformed

    private void searchProduct() {
        LOG.debug("Searching product");
        String str = textFieldBuscar.getText().trim();
        if (str.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese dato a buscar", getTitle(),
                    javax.swing.JOptionPane.WARNING_MESSAGE);

            AppUtils.marcarTextField(textFieldBuscar);
        } else {
            Collection<Product> products;

            switch (searchType) {
                case BY_CODE:
                    int val = AppUtils.toInteger(str);
                    if (val == AppUtils.ERROR_NUMBER) {
                        LOG.warn("Ingrese entero si la busquda es por codigo");

                        javax.swing.JOptionPane.showMessageDialog(this,
                                "Ingrese entero si la busquda es por codigo",
                                getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);

                        AppUtils.marcarTextField(textFieldBuscar);
                        return;
                    } else {
                        LOG.info("Busqueda {}: '{}'", searchType, val);
                        Product product = aProductos.buscarCodigo(val);

                        products = product == null
                                ? Collections.emptyList()
                                : Collections.singletonList(product);
                    }
                    break;

                case BY_NAME:
                    LOG.info("Busqueda {}: '{}'", searchType, str);
                    products = aProductos.buscarNombre(str);
                    break;

                default:
                    throw new IllegalArgumentException("No hay operacion definida para el tipo: " + searchType);
            }

            LOG.info("Mostrando resultado");

            if (products.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se encontraron productos",
                        getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);

                AppUtils.marcarTextField(textFieldBuscar);
            } else {
                mostrarDatos(products);
            }
            AppUtils.marcarTextField(textFieldBuscar);
        }
    }

    private void addProduct() {
        LOG.debug("Adding product");
        JDialogProductForm productForm = new JDialogProductForm(
                javax.swing.JOptionPane.getFrameForComponent(this), new Product());
        productForm.setVisible(true);

        Collection<Product> products = aProductos.buscarNombre(textFieldBuscar.getText());
        LOG.info("Product has been saved, showing data");
        mostrarDatos(products);
    }

    private void radioButtonNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonNombreItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            searchType = SearchType.BY_NAME;
            LOG.trace("Asignando tipo de busqueda por nombre");
            textFieldBuscar.requestFocus();
        }
    }//GEN-LAST:event_radioButtonNombreItemStateChanged

    private void radioButtonCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonCodigoItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            searchType = SearchType.BY_CODE;
            LOG.trace("Asignando tipo de busqueda por codigo");
            textFieldBuscar.requestFocus();
        }
    }//GEN-LAST:event_radioButtonCodigoItemStateChanged

    private void tableProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductsMouseClicked
        LOG.trace(evt.paramString());

        if (evt.getClickCount() == 2) {
            javax.swing.JTable target = (javax.swing.JTable) evt.getSource();
            int row = target.getSelectedRow();

            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) target.getModel();

            Integer productId = (Integer) dtm.getValueAt(row, 0);
            LOG.debug("Getting product identifier {}", productId);

            Product product = aProductos.buscarCodigo(productId);
            JDialogProductForm productForm = new JDialogProductForm(
                    javax.swing.JOptionPane.getFrameForComponent(this), product);
            productForm.showData();
            productForm.setVisible(true);

            Collection<Product> products = aProductos.buscarNombre(textFieldBuscar.getText());
            LOG.info("Product has been updated, showing data");
            mostrarDatos(products);
        }
    }//GEN-LAST:event_tableProductsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel labelTotalRows;
    private javax.swing.JTable tableProducts;
    private javax.swing.JTextField textFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
